### ISSUE TITLE
filtro do por formulário

### ISSUE THREAD

**Issue by Quijaua** [Quijaua/QNinja#1]
Seria bacana colocar um filtro no shortcode de visualização das submissões por formulário, ficando algo assim: [nfsubmissions id=1]

**Comment by edueo** [comment]
Concordo, será implementado.

Att,
Eduardo Alencar

2015-09-01 12:58 GMT-03:00 Quijaua notifications@github.com:

**Comment by Quijaua** [comment]
OK!

Em 2015-09-01 13:02, Eduardo Alencar escreveu:

> Concordo, será implementado.
> 
> Att,
> Eduardo Alencar
> 
> 2015-09-01 12:58 GMT-03:00 Quijaua notifications@github.com:
> 
> > Assigned #1 https://github.com/Quijaua/QNinja/issues/1 to @edueo
> > https://github.com/edueo.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/Quijaua/QNinja/issues/1#event-397968802.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub [1].
> 
>   *
> 
> ## Links:
> 
> [1] https://github.com/Quijaua/QNinja/issues/1#issuecomment-136770465

## 

RAFAEL "BANTO PALMARINO" GOMES
e-mail: rafaelgomes@quijaua.com.br
fone: (19) 8888-0113
Quijaua Soluções Web em Software Livre
http://www.quijaua.com.br [1]

## Links:

[1] http://www.quijaua.com.br/

**Comment by edueo** [comment]
Funcionalidade implementada
[nfsubmissions id=1] - Exibe submissões do form_id = 1
[nfsubmissions] - Exibe todas as submissões

**Comment by Quijaua** [comment]
ótimo!

Em 2015-09-01 16:35, Eduardo Alencar escreveu:

> Funcionalidade implementada
> [nfsubmissions id=1] - Exibe submissões do form_id = 1
> [nfsubmissions] - Exibe todas as submissões
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].
> 
>   *
> 
> ## Links:
> 
> [1] https://github.com/Quijaua/QNinja/issues/1#issuecomment-136835929

## 

RAFAEL "BANTO PALMARINO" GOMES
e-mail: rafaelgomes@quijaua.com.br
fone: (19) 8888-0113
Quijaua Soluções Web em Software Livre
http://www.quijaua.com.br [1]

## Links:

[1] http://www.quijaua.com.br/
