### ISSUE TITLE
miniatura das imagens em galeria

### ISSUE THREAD

**Issue by Quijaua** [Quijaua/QNinja#2]
Ao invés de aparecer o nome da submissão na listagem das imagem colocar uma miniatura da imagem como link

**Comment by edueo** [comment]
dá pra fazer, porém o ninja forms só gera thumbnails se vc marcar a opção
para salvar no media library, sendo assim a miniatura pode parecer
destorcida

Att,
Eduardo Alencar

2015-09-01 12:59 GMT-03:00 Quijaua notifications@github.com:

**Comment by Quijaua** [comment]
ok! pode configurar então levando em consideração que será salvo em 
mídia.

Att.,
Rafael Gomes

Em 2015-09-01 13:03, Eduardo Alencar escreveu:

> dá pra fazer, porém o ninja forms só gera thumbnails se vc marcar a
> opção
> para salvar no media library, sendo assim a miniatura pode parecer
> destorcida
> 
> Att,
> Eduardo Alencar
> 
> 2015-09-01 12:59 GMT-03:00 Quijaua notifications@github.com:
> 
> > Assigned #2 https://github.com/Quijaua/QNinja/issues/2 to @edueo
> > https://github.com/edueo.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/Quijaua/QNinja/issues/2#event-397970452.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub [1].
> 
>   *
> 
> ## Links:
> 
> [1] https://github.com/Quijaua/QNinja/issues/2#issuecomment-136771909

## 

RAFAEL "BANTO PALMARINO" GOMES
e-mail: rafaelgomes@quijaua.com.br
fone: (19) 8888-0113
Quijaua Soluções Web em Software Livre
http://www.quijaua.com.br [1]

## Links:

[1] http://www.quijaua.com.br/

**Comment by edueo** [comment]
Funcionalidade implementada
