### ISSUE TITLE
modal em imagens da galeria

### ISSUE THREAD

**Issue by Quijaua** [Quijaua/QNinja#3]
Não está funcionando o recurso de modal, com o colorbox. Lembrando que deve aparecer a imagem e o título vinculado a submissão.

**Comment by edueo** [comment]
O que acontece exatamente?

Dá algum erro no console? Consegue enviar um print ?

Att,
Eduardo Alencar

2015-09-01 13:07 GMT-03:00 Quijaua notifications@github.com:

**Comment by edueo** [comment]
No meu ambiente aqui a galeria está funcionando normalmente. Por gentileza verificar novamente, e me dá maiores informações sobre o problema.

**Comment by Quijaua** [comment]
OK! Não havia problema mesmo.
