### ISSUE TITLE
Problema em visualização de dados em campo checkbox e lista

### ISSUE THREAD

**Issue by Quijaua** [Quijaua/QNinja#4]
Quando criamos um campo do formulário do tipo checkbox ou
lista, com multi-opção ou uma, aparece assim:

Divulgação feita como? a:3:{i:0;s:6:"Cartaz";i:1;s:8:"Panfleto";i:2;s:15:"Jornal impresso";}

O ideal é aparece assim "Divulgação feita como? Cartaz, Panfleto, Jornal impresso"

**Comment by edueo** [comment]
Implementado
