### ISSUE TITLE
Problema em visualização de dados em campo imagens

### ISSUE THREAD

**Issue by Quijaua** [Quijaua/QNinja#5]
Quando tem uma imagem o ideal é que ela(s) apareça(m) no local e atualmente está aparecendo assim

Coloque aqui fotos da sessão a:1:{s:5:"ZQnr8";a:6:{s:14:"user_file_name";s:23:"foto01_carrossel_01.jpg";s:9:"file_name";s:23:"foto01_carrossel_01.jpg";s:9:"file_path";s:54:"/srv/www/htdocs/cinema/wp-content/uploads/ninja-forms/";s:8:"file_url";s:78:"http://localhost/cinema/wp-content/uploads/ninja-forms/foto01_carrossel_01.jpg";s:8:"complete";s:1:"1";s:9:"upload_id";s:1:"2";}}

**Comment by edueo** [comment]
Corrigido
